package com.co.mywordle

import android.content.Context
import com.co.mywordle.R   // make sure the R import is correct

data class Word(val word: String)

object AppData {

    /** Master list used by the game. Populated once on app start. */
    val words: MutableList<Word> = mutableListOf()

    /** Your existing inline list remains here */
    private val baseWords = listOf(
        Word("CIGAR"), Word("REBUT"), Word("SISSY"),
        Word("HUMPH"), Word("AWAKE"), Word("BLUSH"),
        Word("FOCAL"), Word("EVADE"), Word("NAVAL"),
        Word("SERVE"), Word("HEATH"), Word("DWARF"),
        Word("MODEL"), Word("KARMA"), Word("STINK"),
        Word("GRADE"), Word("QUIET"), Word("BENCH"),
        Word("ABATE"), Word("FEIGN"), Word("MAJOR"),
        Word("DEATH"), Word("FRESH"), Word("CRUST"),
        Word("STOOL"), Word("COLON"), Word("ABASE"),
        Word("MARRY"), Word("REACT"), Word("BATTY"),
        Word("PRIDE"), Word("FLOSS"), Word("HELIX"),
        Word("CROAK"), Word("STAFF"), Word("PAPER"),
        Word("UNFED"), Word("WHELP"), Word("TRAWL"),
        Word("OUTDO"), Word("ADOBE"), Word("CRAZY"),
        Word("SOWER"), Word("REPAY"), Word("DIGIT"),
        Word("CRATE"), Word("CLUCK"), Word("SPIKE"),
        Word("MIMIC"), Word("POUND"), Word("AISLE"),
        Word("ALERT"), Word("ALONE"), Word("APRON"),
        Word("ARISE"), Word("AROMA"), Word("ATOLL"),
        Word("AUDIO"), Word("BAGEL"), Word("BANAL"),
        Word("BANJO"), Word("BARGE"), Word("BASIL"),
        Word("BATCH"), Word("BEACH"), Word("BELCH"),
        Word("BELIE"), Word("BELLY"), Word("BINGE"),
        Word("BISON"), Word("BLADE"), Word("BLANK"),
        Word("BLEND"), Word("BLIMP"), Word("BLOKE"),
        Word("BLOOM"), Word("BLOWN"), Word("BOARD"),
        Word("BOAST"), Word("BOOST"), Word("BRAIN"),
        Word("BRAND"), Word("BRASS"), Word("BREAD"),
        Word("BRICK"), Word("BRIDE"), Word("BRIEF"),
        Word("BRING"), Word("BRISK"), Word("BROAD"),
        Word("BROKE"), Word("BROWN"), Word("BRUSH"),
        Word("BUDDY"), Word("BURST"), Word("CABIN"),
        Word("CABLE"), Word("CANAL"), Word("CANDY"),
        Word("CANOE"), Word("CAROL"), Word("CARRY"),
        Word("CARVE"), Word("CAUSE"), Word("CHAIR"),
        Word("CHAOS"), Word("CHARD"), Word("CHASE"),
        Word("CHEAP"), Word("CHEAT"), Word("CHEER"),
        Word("CHESS"), Word("CHEST"), Word("CHICK"),
        Word("CHIEF"), Word("CHILD"), Word("CHOIR"),
        Word("CIVIC"), Word("CLAIM"), Word("CLAMP"),
        Word("CLASH"), Word("CLASS"), Word("CLEAN"),
        Word("CLEAR"), Word("CLERK"), Word("CLICK"),
        Word("CLIFF"), Word("CLIMB"), Word("CLOAK"),
        Word("CLOTH"), Word("CLOUD"), Word("COAST"),
        Word("COBRA"), Word("COMIC"), Word("CORAL"),
        Word("COVER"), Word("CRACK"), Word("CRAFT"),
        Word("CRANE"), Word("CRASH"), Word("CRAWL"),
        Word("CRIME"), Word("CROSS"), Word("CROWD"),
        Word("CROWN"), Word("CRUSH"), Word("CURVE"),
        Word("CYCLE"), Word("DAILY"), Word("DAIRY"),
        Word("DANCE"), Word("DEALT"), Word("DELTA"),
        Word("DIARY"), Word("DODGE"), Word("DRAFT"),
        Word("DRAWN"), Word("DREAM"), Word("DRESS"),
        Word("DRIFT"), Word("DRINK"), Word("DRIVE"),
        Word("DROVE"), Word("DROWN"), Word("EARLY"),
        Word("EARTH"), Word("EATER"), Word("EIGHT"),
        Word("ELDER"), Word("ELITE"), Word("ENJOY"),
        Word("ENTER"), Word("ENTRY"), Word("ERROR"),
        Word("EVENT"), Word("EVERY"), Word("EXACT"),
        Word("EXIST"), Word("EXTRA"), Word("FAITH"),
        Word("FALSE"), Word("FANCY"), Word("FAULT"),
        Word("FAVOR"), Word("FEAST"), Word("FELON"),
        Word("FENCE"), Word("FETCH"), Word("FIELD"),
        Word("FIERY"), Word("FINAL"), Word("FIRST"),
        Word("FLAIR"), Word("FLAME"), Word("FLASH"),
        Word("FLEET"), Word("FLOOD"), Word("FLOUR"),
        Word("FLUTE"), Word("FOAMY"), Word("FORCE"),
        Word("FORGO"), Word("FORUM"), Word("FOUND"),
        Word("FRAME"), Word("FRANK"), Word("FRAUD"),
        Word("FREAK"), Word("FRONT"), Word("FRUIT"),
        Word("GAFFE"), Word("GAMER"), Word("GHOST"),
        Word("GIANT"), Word("GLOBE"), Word("GLOOM"),
        Word("GLORY"), Word("GRACE"), Word("GRAND"),
        Word("GRAPE"), Word("GRAPH"), Word("GRASS"),
        Word("GRATE"), Word("GRAVE"), Word("GREEN"),
        Word("GRILL"), Word("GROAN"), Word("GROVE"),
        Word("GUARD"), Word("GUEST"), Word("GUIDE"),
        Word("GUILT"), Word("HABIT"), Word("HAPPY"),
        Word("HARSH"), Word("HAUNT"), Word("HAZEL"),
        Word("HEART"), Word("HINGE"), Word("HORSE"),
        Word("HOVER"), Word("HUMAN"), Word("HUMID"),
        Word("HUMOR"), Word("HURRY"), Word("ICING"),
        Word("IDEAL"), Word("IMAGE"), Word("IMPLY"),
        Word("INDEX"), Word("INNER"), Word("INPUT"),
        Word("ISSUE"), Word("JOINT"), Word("JUDGE"),
        Word("JUICE"), Word("KNIFE"), Word("LABEL"),
        Word("LARGE"), Word("LASER"), Word("LATER"),
        Word("LAUGH"), Word("LEMON"), Word("LEVEL"),
        Word("LIGHT"), Word("LIMIT"), Word("LINEN"),
        Word("LIVER"), Word("LOCAL"), Word("LOGIC"),
        Word("LOOSE"), Word("LUCKY"), Word("LUNCH"),
        Word("MAGIC"), Word("MAJOR"), Word("MAKER"),
        Word("MANGO"), Word("MAPLE"), Word("MARCH"),
        Word("MATCH"), Word("MAYOR"), Word("MEDAL"),
        Word("MERIT"), Word("METAL"), Word("MIGHT"),
        Word("MINOR"), Word("MIXED"), Word("MODEL"),
        Word("MONEY"), Word("MONTH"), Word("MORAL"),
        Word("MOTOR"), Word("MOUSE"), Word("MOUTH"),
        Word("MUSIC"), Word("NAIVE"), Word("NEEDS"),
        Word("NEVER"), Word("NIGHT"), Word("NOISE"),
        Word("NORTH"), Word("NOVEL"), Word("NURSE"),
        Word("OCEAN"), Word("OFFER"), Word("OFTEN"),
        Word("OPERA"), Word("ORDER"), Word("ORGAN"),
        Word("OTHER"), Word("OUTER"), Word("OWNER"),
        Word("PAINT"), Word("PAUSE"), Word("PEACE"),
        Word("PHASE"), Word("PHONE"), Word("PHOTO"),
        Word("PIANO"), Word("PIECE"), Word("PILOT"),
        Word("PIZZA"), Word("PLACE"), Word("PLAIN"),
        Word("PLANT"), Word("PLATE"), Word("POINT"),
        Word("POKER"), Word("POLAR"), Word("POLICY"),
        Word("POWER"), Word("PRESS"), Word("PRICE"),
        Word("PRIDE"), Word("PRIME"), Word("PRINT"),
        Word("PRIZE"), Word("PROOF"), Word("PROUD"),
        Word("PROVE"), Word("PULSE"), Word("PUPIL"),
        Word("PURSE"), Word("QUEEN"), Word("QUERY"),
        Word("QUICK"), Word("QUIET"), Word("QUITE"),
        Word("RADAR"), Word("RADIO"), Word("RAISE"),
        Word("RANGE"), Word("RAPID"), Word("RATIO"),
        Word("REACT"), Word("READY"), Word("REACH"),
        Word("REBEL"), Word("REIGN"), Word("RELAX"),
        Word("RENEW"), Word("REPLY"), Word("RESET"),
        Word("RESIN"), Word("RIGHT"), Word("RIVER"),
        Word("ROBOT"), Word("ROUGH"), Word("ROUND"),
        Word("ROUTE"), Word("ROYAL"), Word("RUGBY"),
        Word("RULES"), Word("RURAL"), Word("SCALE"),
        Word("SCENE"), Word("SCOPE"), Word("SCORE"),
        Word("SCOUT"), Word("SCREW"), Word("SEASON"),
        Word("SECOND"), Word("SENSE"), Word("SERVE"),
        Word("SHADE"), Word("SHAKE"), Word("SHARE"),
        Word("SHARK"), Word("SHEEP"), Word("SHEET"),
        Word("SHELF"), Word("SHIFT"), Word("SHINE"),
        Word("SHIRT"), Word("SHOCK"), Word("SHOOT"),
        Word("SHORT"), Word("SHOUT"), Word("SHOWN"),
        Word("SHRUB"), Word("SIGHT"), Word("SIGMA"),
        Word("SILLY"), Word("SINCE"), Word("SKILL"),
        Word("SKIRT"), Word("SKULL"), Word("SLAVE"),
        Word("SLEEP"), Word("SLICE"), Word("SLIDE"),
        Word("SMALL"), Word("SMART"), Word("SMILE"),
        Word("SMOKE"), Word("SNAKE"), Word("SOLAR"),
        Word("SOLID"), Word("SOLVE"), Word("SOUND"),
        Word("SPACE"), Word("SPARE"), Word("SPEAK"),
        Word("SPEED"), Word("SPELL"), Word("SPEND"),
        Word("SPICE"), Word("SPINE"), Word("SPITE"),
        Word("SPLIT"), Word("SPOIL"), Word("SPORT"),
        Word("SPRAY"), Word("SPREAD"), Word("SPRING"),
        Word("SQUAD"), Word("SQUAT"), Word("STACK"),
        Word("STAFF"), Word("STAGE"), Word("STAKE"),
        Word("STAMP"), Word("STAND"), Word("STARE"),
        Word("STATE"), Word("STEAK"), Word("STEAL"),
        Word("STEAM"), Word("STEEL"), Word("STICK"),
        Word("STILL"), Word("STOCK"), Word("STONE"),
        Word("STORE"), Word("STORM"), Word("STORY"),
        Word("STRAP"), Word("STRAW"), Word("STUDY"),
        Word("STUFF"), Word("STYLE"), Word("SUGAR"),
        Word("SUPER"), Word("SWEAR"), Word("SWEET"),
        Word("SWIFT"), Word("SWING"), Word("SWORD"),
        Word("TABLE"), Word("TAKEN"), Word("TASTE"),
        Word("TEACH"), Word("TEARS"), Word("TEETH"),
        Word("TENSE"), Word("THANK"), Word("THEME"),
        Word("THICK"), Word("THING"), Word("THINK"),
        Word("THIRD"), Word("THOSE"), Word("THREE"),
        Word("THROW"), Word("TIGHT"), Word("TIMES"),
        Word("TIRED"), Word("TITLE"), Word("TODAY"),
        Word("TOKEN"), Word("TONES"), Word("TOOLS"),
        Word("TOPIC"), Word("TOTAL"), Word("TOUCH"),
        Word("TOUGH"), Word("TOWER"), Word("TRACK"),
        Word("TRADE"), Word("TRAIL"), Word("TRAIN"),
        Word("TRIAL"), Word("TRICK"), Word("TRIED"),
        Word("TRUCK"), Word("TRULY"), Word("TRUST"),
        Word("TRUTH"), Word("TWICE"), Word("UNDER"),
        Word("UNION"), Word("UNITY"), Word("UNTIL"),
        Word("UPPER"), Word("URBAN"), Word("USAGE"),
        Word("USUAL"), Word("VALUE"), Word("VAPOR"),
        Word("VENOM"), Word("VIDEO"), Word("VIRUS"),
        Word("VISIT"), Word("VITAL"), Word("VOICE"),
        Word("VOTER"), Word("WAGON"), Word("WAIST"),
        Word("WASTE"), Word("WATCH"), Word("WATER"),
        Word("WEIGH"), Word("WEIRD"), Word("WHALE"),
        Word("WHEAT"), Word("WHERE"), Word("WHILE"),
        Word("WHITE"), Word("WHOLE"), Word("WHOSE"),
        Word("WOMAN"), Word("WORLD"), Word("WORST"),
        Word("WORTH"), Word("WOULD"), Word("WOUND"),
        Word("WRITE"), Word("WRONG"), Word("YACHT"),
        Word("YEARN"), Word("YEAST"), Word("YIELD"),
        Word("YOUNG"), Word("YOUTH"), Word("ZEBRA"),
        Word("ZONED"), Word("ZONES"), Word("APPLE"),
        Word("ADIEU")

    )

    /**
     * Call once (e.g. in MainActivity.onCreate) with `applicationContext`.
     * Combines the inline list with any extra words found in res/raw/wordlist.txt.
     */
    fun initWords(context: Context) {
        if (words.isNotEmpty()) return            // already initialised

        // 1. Add built-in list
        words += baseWords

        // 2. Read additional words from raw resource
        context.resources.openRawResource(R.raw.wordlist).bufferedReader().useLines { lines ->
            lines.map { it.trim().uppercase() }
                .filter { it.length == 5 }       // only 5-letter words
                .distinct()
                .forEach { w ->
                    if (words.none { it.word == w }) {
                        words += Word(w)         // only add if not in the list yet
                    }
                }
        }
    }
}