package com.co.mywordle

data class Word (val word: String)

class AppData {
    companion object {
        val words: MutableList<Word> = mutableListOf()

        fun initWords() {
            words.clear()
            words.addAll(listOf(
                Word("CIGAR"), Word("REBUT"), Word("SISSY"),
                Word("HUMPH"), Word("AWAKE"), Word("BLUSH"),
                Word("FOCAL"), Word("EVADE"), Word("NAVAL"),
                Word("SERVE"), Word("HEATH"), Word("DWARF"),
                Word("MODEL"), Word("KARMA"), Word("STINK"),
                Word("GRADE"), Word("QUIET"), Word("BENCH"),
                Word("ABATE"), Word("FEIGN"), Word("MAJOR"),
                Word("DEATH"), Word("FRESH"), Word("CRUST"),
                Word("STOOL"), Word("COLON"), Word("ABASE"),
                Word("MARRY"), Word("REACT"), Word("BATTY"),
                Word("PRIDE"), Word("FLOSS"), Word("HELIX"),
                Word("CROAK"), Word("STAFF"), Word("PAPER"),
                Word("UNFED"), Word("WHELP"), Word("TRAWL"),
                Word("OUTDO"), Word("ADOBE"), Word("CRAZY"),
                Word("SOWER"), Word("REPAY"), Word("DIGIT"),
                Word("CRATE"), Word("CLUCK"), Word("SPIKE"),
                Word("MIMIC"), Word("POUND"), Word("AISLE"),
                Word("ALERT"), Word("ALONE"), Word("APRON"),
                Word("ARISE"), Word("AROMA"), Word("ATOLL"),
                Word("AUDIO"), Word("BAGEL"), Word("BANAL"),
                Word("BANJO"), Word("BARGE"), Word("BASIL"),
                Word("BATCH"), Word("BEACH"), Word("BELCH"),
                Word("BELIE"), Word("BELLY"), Word("BINGE"),
                Word("BISON"), Word("BLADE"), Word("BLANK"),
                Word("BLEND"), Word("BLIMP"), Word("BLOKE"),
                Word("BLOOM"), Word("BLOWN"), Word("BOARD"),
                Word("BOAST"), Word("BOOST"), Word("BRAIN"),
                Word("BRAND"), Word("BRASS"), Word("BREAD"),
                Word("BRICK"), Word("BRIDE"), Word("BRIEF"),
                Word("BRING"), Word("BRISK"), Word("BROAD"),
                Word("BROKE"), Word("BROWN"), Word("BRUSH"),
                Word("BUDDY"), Word("BURST"), Word("CABIN"),
                Word("CABLE"), Word("CANAL"), Word("CANDY"),
                Word("CANOE"), Word("CAROL"), Word("CARRY"),
                Word("CARVE"), Word("CAUSE"), Word("CHAIR"),
                Word("CHAOS"), Word("CHARD"), Word("CHASE"),
                Word("CHEAP"), Word("CHEAT"), Word("CHEER"),
                Word("CHESS"), Word("CHEST"), Word("CHICK"),
                Word("CHIEF"), Word("CHILD"), Word("CHOIR"),
                Word("CIVIC"), Word("CLAIM"), Word("CLAMP"),
                Word("CLASH"), Word("CLASS"), Word("CLEAN"),
                Word("CLEAR"), Word("CLERK"), Word("CLICK"),
                Word("CLIFF"), Word("CLIMB"), Word("CLOAK"),
                Word("CLOTH"), Word("CLOUD"), Word("COAST"),
                Word("COBRA"), Word("COMIC"), Word("CORAL"),
                Word("COVER"), Word("CRACK"), Word("CRAFT"),
                Word("CRANE"), Word("CRASH"), Word("CRAWL"),
                Word("CRIME"), Word("CROSS"), Word("CROWD"),
                Word("CROWN"), Word("CRUSH"), Word("CURVE"),
                Word("CYCLE"), Word("DAILY"), Word("DAIRY"),
                Word("DANCE"), Word("DEALT"), Word("DELTA"),
                Word("DIARY"), Word("DODGE"), Word("DRAFT"),
                Word("DRAWN"), Word("DREAM"), Word("DRESS"),
                Word("DRIFT"), Word("DRINK"), Word("DRIVE"),
                Word("DROVE"), Word("DROWN"), Word("EARLY"),
                Word("EARTH"), Word("EATER"), Word("EIGHT"),
                Word("ELDER"), Word("ELITE"), Word("ENJOY"),
                Word("ENTER"), Word("ENTRY"), Word("ERROR"),
                Word("EVENT"), Word("EVERY"), Word("EXACT"),
                Word("EXIST"), Word("EXTRA"), Word("FAITH"),
                Word("FALSE"), Word("FANCY"), Word("FAULT"),
                Word("FAVOR"), Word("FEAST"), Word("FELON"),
                Word("FENCE"), Word("FETCH"), Word("FIELD"),
                Word("FIERY"), Word("FINAL"), Word("FIRST"),
                Word("FLAIR"), Word("FLAME"), Word("FLASH"),
                Word("FLEET"), Word("FLOOD"), Word("FLOUR"),
                Word("FLUTE"), Word("FOAMY"), Word("FORCE"),
                Word("FORGO"), Word("FORUM"), Word("FOUND"),
                Word("FRAME"), Word("FRANK"), Word("FRAUD"),
                Word("FREAK"), Word("FRONT"), Word("FRUIT"),
                Word("GAFFE"), Word("GAMER"), Word("GHOST"),
                Word("GIANT"), Word("GLOBE"), Word("GLOOM"),
                Word("GLORY"), Word("GRACE"), Word("GRAND"),
                Word("GRAPE"), Word("GRAPH"), Word("GRASS"),
                Word("GRATE"), Word("GRAVE"), Word("GREEN"),
                Word("GRILL"), Word("GROAN"), Word("GROVE"),
                Word("GUARD"), Word("GUEST"), Word("GUIDE"),
                Word("GUILT"), Word("HABIT"), Word("HAPPY"),
                Word("HARSH"), Word("HAUNT"), Word("HAZEL"),
                Word("HEART"), Word("HINGE"), Word("HORSE"),
                Word("HOVER"), Word("HUMAN"), Word("HUMID"),
                Word("HUMOR"), Word("HURRY"), Word("ICING"),
                Word("IDEAL"), Word("IMAGE"), Word("IMPLY"),
                Word("ADIEU"), Word("LEAST"), Word("PLANE"),
                Word("DOUGH"), Word("START"), Word("STARS"),
                Word("RAILS"), Word("PARTY"), Word("SMART"),
                Word("GNOME"), Word("RACKS"), Word("WALLS"),
                Word("FARTY"), Word("RUSTY"), Word("RALLY"),
                Word("CRAVE")
            ))
        }
    }
}